Funcionalidade: Compra

Cenario: Simular uma compra com um usuario existente
  Dado que eu esteja na home e logado
  Quando eu clicar em "T-shirts"
    E parar o mouse encima do "Fedad short Sleeve T-shirts"
    E clique em "Fedad short Sleeve T- shirts"
    E Clicar em "Quantity"  e altere a quantida
    E clicar em "Size" e selecionar tamanho
    E clicar em  "Cor" 
    E Clicar em "Add to cart"
    E clicar em "Proceed to chekout"
    E clicar em "Proceed to chekout"
    E clicar em "Proceed to chekout"
    E selecionar "Terms  of service" 
    E clicar em "Proceed to chekout"
    E Clicar em  "Pay by check order processing wil be longer"
    E clicar em  "I confirm my order"
    Entao a comprar sera realizada com sucesso 
